services:
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=ckan_default
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=ckan_default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan_default", "-d", "ckan_default"]

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8081:8080

  solr:
    build:
      context: ../
      dockerfile: docker/Dockerfile.solr
    volumes:
      - ./data/solr_data:/var/solr
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  ckan:
    depends_on:
      - postgres
      - solr
      - redis
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - dev.env
    volumes:
      - ./data/ckan:/var/lib/ckan/default
      - ../ckan:/app/ckan
    ports:
      - 8000:8000
    command: ./docker/entrypoint-dev.sh

  xloader:
    depends_on:
      - ckan
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - dev.env
    command: ./docker/entrypoint-worker.sh

  redis:
    image: redis:7
