tags = [
    {
        "vocabulary": "target",
        "label": "Target",
        "tags": ["DNA", "RNA", "Protein", "Small Molecule"],
    },
    {
        "vocabulary": "assay_type",
        "label": "Sequencing Technology",
        "tags": [
            "Short Read",
            "Long Read",
            "DNA-Binding / Chromatin",
            "Methylation",
            "Spatial",
            "Single Cell",
        ],
    },
    {
        "vocabulary": "imaging",
        "label": "Imaging Technology",
        "tags": [
            "Fixed Cells / Tissues",
            "Live Cells",
            "Fluorescence",
            "Multiplexing",
            "In Vivo",
            "Pre-Clinical",
        ],
    },
    {
        "vocabulary": "molecules",
        "label": "Molecule and Cell Technology",
        "tags": ["Flow Sorting / Analysis", "Mass Spec"],
    },
    {
        "vocabulary": "source",
        "label": "Organism",
        "tags": [
            "Human",
            "Mouse",
            "Bacteria",
            "Virus",
        ],
    },
    {
        "vocabulary": "tissue",
        "label": "Tissue",
        "tags": [
            "Blood",
            "Tumour",
            "Liver",
            "Pancreas",
            "Prostate",
            "Breast",
            "Kidney",
            "Heart",
            "Spleen",
            "Nodes",
            "Lung ",
            "Skin",
            "Bone",
            "Saliva",
            "Brain",
            "Glands",
        ],
    },
    {
        "vocabulary": "factor",
        "label": "Experimental Characteristics",
        "tags": [
            "FFPE",
            "Fresh Frozen",
            "Time course",
            "In Vitro",
            "In Vivo",
            "Cell Line: Immortal",
            "Cell Line: Primary",
            "DPX",
            "PDX",
        ],
    },
]
