tags = [
    {
        "vocabulary": "assay_type",
        "label": "Assay Type",
        "tags": [
            "Bisulfite",
            "WGS",
            "miRNA-seq",
            "Exome",
            "RNA-Seq",
            "Spatial Transcriptomics",
            "Mass Spec",
            "GWAS",
            "scRNA-Seq",
            "FLIM",
            "FACS",
            "CRISPR",
        ],
    },
    {
        "vocabulary": "source",
        "label": "Source",
        "tags": [
            "Human",
            "Mouse",
            "Rat",
            "Worm",
            "Fish",
            "Bacteria",
            "Virus",
        ],
    },
    {
        "vocabulary": "tissue",
        "label": "Tissue",
        "tags": [
            "Blood",
            "Tumour",
            "Liver",
            "Pancreas",
            "Prostate",
            "Breast",
            "Whole Organism",
            "Kidney",
            "Heart",
            "Spleen",
            "Nodes",
            "Lung ",
            "Ovary",
            "Skin",
            "Bone",
            "Eye",
            "Adipose tissue",
            "Saliva",
            "Brain",
            "Glands",
            "Feaces",
        ],
    },
    {
        "vocabulary": "factor",
        "label": "Other",
        "tags": [
            "Healthly controls",
            "Biobank",
            "FFPE",
            "Fresh Frozen",
            "Time course",
        ],
    },
    {
        "vocabulary": "cell_line",
        "label": "Cell Line",
        "tags": [
            "Immortal",
            "Primary",
        ],
    },
]
