name: dev release
on:
  workflow_run:
    workflows: [Cypress]
    types:
      - completed
    branches: [garvan]

permissions:
  contents: "read"
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set SHA_SHORT
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: authenticate to google cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1008866204922/locations/global/workloadIdentityPools/ckan-gh-identity-pool/providers/ckan-gh-provider"
          service_account: datahub-sa@garvan-data-hub-dev.iam.gserviceaccount.com

      - name: "setup gcloud sdk"
        uses: google-github-actions/setup-gcloud@v0

      - name: "Docker auth"
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: garvan-data-hub-dev-gke
          location: australia-southeast1-a
          project_id: garvan-data-hub-dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/ckan:latest
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/ckan:${{steps.vars.outputs.sha_short}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy backend
        run: |-
          kubectl set image deployment/ckan-dev ckan-dev="australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/ckan:${{steps.vars.outputs.sha_short}}"
