name: prod release
on:
  release:
    types: [published]

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set SHA_SHORT
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: authenticate to google cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1008866204922/locations/global/workloadIdentityPools/ckan-gh-identity-pool/providers/ckan-gh-provider"
          service_account: datahub-sa@garvan-data-hub-dev.iam.gserviceaccount.com

      - name: "setup gcloud sdk"
        uses: google-github-actions/setup-gcloud@v0

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: garvan-data-hub-dev-gke
          location: australia-southeast1-a
          project_id: garvan-data-hub-dev

      - name: Deploy backend
        run: |-
          kubectl set image deployment/ckan-dev ckan="australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/ckan:${{steps.vars.outputs.sha_short}}"
          kubectl set image deployment/worker-dev worker="australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/ckan:${{steps.vars.outputs.sha_short}}"
